version: '3.7'
services:
  proxy:
    image: nginx
    volumes:
    - ./proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 80:80
    depends_on:
      - static
      - api
      - pushpin
    restart: unless-stopped
  static:
    image: julianpoy/recipesage-selfhost:static-v2.11.0-beta5
    environment:
      - API_BASE_OVERRIDE=null
    volumes:
      - ./static.entrypoint.sh:/docker-entrypoint.d/static.entrypoint.sh
    restart: unless-stopped
  api:
    image: julianpoy/recipesage-selfhost:api-v2.11.0-beta5
    depends_on:
      - postgres
      - elasticsearch
      - pushpin
      - browserless
    command: /app/www
    environment:
      - STORAGE_TYPE=filesystem
      - FILESYSTEM_STORAGE_PATH=/rs-media
      - NODE_ENV=selfhost
      - VERBOSE=false
      - VERSION=selfhost
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgres
      - POSTGRES_SSL=false
      - POSTGRES_LOGGING=false
      - GCM_KEYPAIR
      - SENTRY_DSN
      - GRIP_URL=http://pushpin:5561/
      - GRIP_KEY=changeme
      - SEARCH_PROVIDER=elasticsearch
      - ELASTIC_CONN=http://elastic:recipesage_selfhost@elasticsearch:9200
      - ELASTIC_PASSWORD=recipesage_selfhost
      - STRIPE_SK
      - STRIPE_WEBHOOK_SECRET
      - BROWSERLESS_HOST=browserless
      - BROWSERLESS_PORT=3000
      - INGREDIENT_INSTRUCTION_CLASSIFIER_URL=http://ingredient-instruction-classifier:3000/
    volumes:
      - ./data/api-files:/rs-media
    restart: unless-stopped
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1500m -Xmx1500m"
      - ELASTIC_PASSWORD=recipesage_selfhost
      - xpack.security.enabled=false
    volumes:
      - elasticsearchdata:/usr/share/elasticsearch/data
    restart: unless-stopped
  pushpin:
    image: fanout/pushpin:1.27.0
    environment:
      - target=api:3000
    restart: unless-stopped
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=recipesage_selfhost
      - POSTGRES_USER=recipesage_selfhost
      - POSTGRES_PASSWORD=recipesage_selfhost
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
  browserless:
    image: browserless/chrome:1.53.0-chrome-stable
    environment:
      - MAX_CONCURRENT_SESSIONS=3
      - MAX_QUEUE_LENGTH=10
    restart: unless-stopped
  ingredient-instruction-classifier:
    image: julianpoy/ingredient-instruction-classifier:latest
    environment:
      - SENTENCE_EMBEDDING_BATCH_SIZE=200
      - PREDICTION_CONCURRENCY=4
    restart: unless-stopped
volumes:
  elasticsearchdata:
    driver: local
